### PR TITLE
created PowerShell script that is more flexible

### PR DESCRIPTION
**Pull request by protectivedad**
Not sure if you are open to a Powershell version but here it is if you want to add it. The benefits are that it should work on different languages (I used it for en-GB) and architectures (arm64 and amd64)

I used it on 1702 it should work on all the versions your scripts work on also.

### CODE REVIEW

**Comment by Anonymous-Ol** [comment]
This is the most amazing thing. I wanted to use tiny11 on a more recent iso, and this was the perfect tool for the job. The only real question is why NTDEV hasn't merged it.

**Comment by protectivedad** [comment]
> This is the most amazing thing. I wanted to use tiny11 on a more recent iso, and this was the perfect tool for the job.

Glad it worked out for you.

**Comment by grandpa1946** [comment]
i think that he doesn't look at his github at all

**Comment by grandpa1946** [comment]
@protectivedad tysm this is just way better! the way i did it was really long with getting the provisioned appxpackages etc with dism but you method is just really fast and is compatible with all versions!

**Pull request closed without merging**
