### PR TITLE
Support any future changes in packages

### PR DESCRIPTION
**Pull request by SecSamDev**
I have migrated the script to powershell adding some simplifications as to never need to update the script for future versions/builds of Windows 11.

### CODE REVIEW

**Comment by megapro17** [comment]
That's very nice! Does it work on the latest build?

**Comment by megapro17** [comment]
and theres powershell version already lol https://github.com/ianis58/tiny11builder

**Comment by 0xDEADFED5** [comment]
oh shit, lol, i just created my own powershell version at https://github.com/0xDEADFED5/ps_tiny11

**Comment by SecSamDev** [comment]
Maybe it is a good idea, given that many others have come from this repository, to update and unify the script to support more functionalities.

**Comment by nivranaitsirhc** [comment]
[I have an offshoot that allows you to select multiple image into one iso written in PS. Plus you can modify the package list thru an ini file.](https://github.com/nivranaitsirhc/WindowsSlimBuilder)

**Pull request closed without merging**
